// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for AssignmentStatus.
const (
	AssignmentStatusActive    AssignmentStatus = "active"
	AssignmentStatusCompleted AssignmentStatus = "completed"
	AssignmentStatusPending   AssignmentStatus = "pending"
)

// Defines values for ListAssignmentsParamsStatus.
const (
	ListAssignmentsParamsStatusActive    ListAssignmentsParamsStatus = "active"
	ListAssignmentsParamsStatusCompleted ListAssignmentsParamsStatus = "completed"
	ListAssignmentsParamsStatusPending   ListAssignmentsParamsStatus = "pending"
)

// Assignment defines model for Assignment.
type Assignment struct {
	CreatedAt *time.Time       `json:"createdAt,omitempty"`
	Id        *string          `json:"id,omitempty"`
	RouteId   string           `json:"routeId"`
	StartsAt  time.Time        `json:"startsAt"`
	Status    AssignmentStatus `json:"status"`
	UpdatedAt *time.Time       `json:"updatedAt,omitempty"`
	VehicleId string           `json:"vehicleId"`
}

// AssignmentStatus defines model for Assignment.Status.
type AssignmentStatus string

// EntityMetadata defines model for EntityMetadata.
type EntityMetadata struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        *string    `json:"id,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewAssignment defines model for NewAssignment.
type NewAssignment struct {
	RouteId   string    `json:"routeId"`
	StartsAt  time.Time `json:"startsAt"`
	VehicleId string    `json:"vehicleId"`
}

// BadRequest defines model for BadRequest.
type BadRequest struct {
	Details *string `json:"details,omitempty"`
	Error   *string `json:"error,omitempty"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Error *string `json:"error,omitempty"`
}

// ListAssignmentsParams defines parameters for ListAssignments.
type ListAssignmentsParams struct {
	Status *ListAssignmentsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListAssignmentsParamsStatus defines parameters for ListAssignments.
type ListAssignmentsParamsStatus string

// CreateAssignmentJSONRequestBody defines body for CreateAssignment for application/json ContentType.
type CreateAssignmentJSONRequestBody = NewAssignment
