// Code generated by avro/gen. DO NOT EDIT.
package avro

// AssignmentCreated is a generated struct.
type AssignmentCreated struct {
	AssignmentID string  `avro:"assignmentId"`
	VehicleID    string  `avro:"vehicleId"`
	RouteID      string  `avro:"routeId"`
	Timestamp    string  `avro:"timestamp"`
	DriverID     *string `avro:"driverId"`
}
